[package]
name = "k8s-autodeploy"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
reqwest = { version = "0.11", features=["json"]}
serde = {version = "1", features=["derive"]}
once_cell = "1.8"
chrono = {version = "0.4", features=["serde"]}
serde_json = "1.0"